# Name of your application. Used to uniquely configure containers.
service: komadome

# Name of the container image.
image: <%= ENV['IMAGE_NAME']%>

# Deploy to these servers.
servers:
  web:
    hosts:
      - <%= ENV['PRIMARY_HOST'] %>
  cron:
    hosts:
      - <%= ENV['PRIMARY_HOST'] %>
    cmd: bash -c "env > /etc/environment && cron -f"
    options:
      user: root

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: <%= ENV['REGISTRY_USER'] %>
  # Always use an access token rather than real password when possible.
  password:
    - MRSK_REGISTRY_PASSWORD

env:
  clear:
    RAILS_LOG_TO_STDOUT: '1'
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_HOST
    - DATABASE_PORT
    - DATABASE_USER
    - DATABASE_PASS
    - DATABASE_NAME
    - SKYLIGHT_AUTHENTICATION
    - MAIN_SITE_URL
    - SITE_NAME
    - RECEPTION_EMAIL
    - RSYNC_PASS_FILE
    - RSYNC_SERVER_PATH
    - CK_TOKEN
    - SKYLIGHT_AUTHENTICATION

# Use a different ssh user than root
ssh:
  user: deploy

# Configure builder setup.
# builder:
#   args:
#     RUBY_VERSION: 3.2.0
#   secrets:
#     - GITHUB_TOKEN
#   remote:
#     arch: amd64
#     host: ssh://app@192.168.0.1

builder:
  dockerfile: Dockerfile.production
  arch: amd64
  local: true

proxy:
  host: <%= ENV['PROXY_HOST'] %>
  app_port: 3000
  ssl: true
  healthcheck:
    interval: 30
    timeout: 10
